import Footer from '@/components/Footer';
import './globals.css';
import { Inter, Playfair_Display } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });
const playfair = Playfair_Display({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
